[global]
developmentMode = false
suppressDeprecationWarnings = true

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
runOnSave = false

[browser]
gatherUsageStats = false

[logger]
level = "warning"
